# Generated by Django 2.2 on 2019-06-10 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('visible', models.BooleanField(default=True)),
                ('usernameR', models.CharField(default='Invalid', max_length=100, primary_key=True, serialize=False)),
                ('following', models.ManyToManyField(null=True, related_name='_userextended_following_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
