# Generated by Django 2.2 on 2019-06-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextendedr',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
