# Generated by Django 2.2 on 2019-06-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='emailR',
            field=models.EmailField(blank=True, max_length=20),
        ),
    ]
