# Generated by Django 2.2 on 2019-06-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userm', '0002_auto_20190627_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextendedr',
            name='aboutme',
            field=models.CharField(max_length=200, null=True, verbose_name='bio'),
        ),
    ]
