# Generated by Django 2.2 on 2019-06-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userm', '0002_userextended_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
