# Generated by Django 2.2 on 2019-06-27 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userm', '0003_auto_20190627_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextendedr',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='userextendedr',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='userextendedr',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='userextendedr',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is staff'),
        ),
        migrations.AlterField(
            model_name='userextendedr',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='is superuser'),
        ),
        migrations.AlterField(
            model_name='userextendedr',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='username'),
        ),
    ]
