# Generated by Django 2.2 on 2019-06-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userm', '0004_auto_20190627_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextendedr',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='avatar'),
        ),
    ]
